parameters:
    contentonthefly.controller.location.class: EzSystems\EzContentOnTheFlyBundle\Controller\LocationController

services:
    contentonthefly.controller.location:
        class: '%contentonthefly.controller.location.class%'
        arguments:
            - '@ezpublish.api.service.location'
            - '@logger'
        calls:
            - [setConfiguration, ['$content;content_on_the_fly$']]
